env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[aba8cc7c492ddfc8ac24e8131de7d088b552d7878a1b1b8737dd4e284b7a289aad2dfe5a4db70ab4dda84080c471111e]"
    bot_api: "ENCRYPTED[f200c3ff20251c1c2eb9fcb192c26a367e83a21bd64ca93cc97d4a06bc16c843636d19ded2fe63588f81d4718a9e9bd5]"

task:
    name: Rimuru # Project name
    timeout_in: 120m
    container:
      image: RidwanAdiCahyono/build:latest
      cpu: 8
      memory: 32G

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - rclone copy ItoRenz:Rimuru/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
      - cd /tmp/rom
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
